name: Run MATLAB Script on github runner 
on:
  workflow_dispatch:

jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: get number of cores
        run: "nproc --all"
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: Run script
#         uses: matlab-actions/run-command@v1
#         with:
#           command: myscript
      
