name: Run MATLAB Script on github runner 
on:
#   workflow_dispatch:
  push:

jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: download octave
        run: "sudo apt-get install octave; octPath=$(which octave); cp $octPath ."
        
      - name: save octave as artifact
        uses: actions/upload-artifact@v3
        with:
          name: octave
          path: octave
        
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: Run script
#         uses: matlab-actions/run-command@v1
#         with:
#           command: myscript
      
