name: Run MATLAB Script on github runner 
on:
  workflow_dispatch:

jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: download octave
        run: "sudo apt-get install octave"
      - name: make matlab file
        run: "echo '1:5' > test.m"
      - name: run octave
        run: octave test.m
      
